[build]
  publish = "public"

[[redirects]]
  from = "/cozinha"
  to = "/cozinha.html"
  status = 200
[[redirects]]
  from = "/banheiro"
  to = "/banheiro.html"
  status = 200
[[redirects]]
  from = "/ferramentas"
  to = "/ferramentas.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
